# -*- coding: utf-8 -*-
"""PREDICTIVE ANALYTICS FOR CUSTOMER PURCHASE BEHAVIOUR USING MACHINE LEARNING IN E-COMMERCE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1494GDD4zUMjxht9K32Wkwd97HIgdEmct
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,roc_curve,confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB

import xgboost as xgb
import shap
import joblib
import warnings
warnings.filterwarnings('ignore',category=FutureWarning)

df = pd.read_csv("customer_purchase_data.csv")

df.head()

df["DiscountsAvailed"].value_counts()

df.shape

df.columns

df.info()

df.describe()

"""# **Handle Missing Values**"""

df.isnull().sum()

"""# **Outlier Detection**"""

numeric_cols = df.select_dtypes(include=np.number).columns
outlier_summary = {}

for col in numeric_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    outlier_summary[col] = len(outliers)

# Display number of outliers in each column
outlier_df = pd.DataFrame((outlier_summary.items()), columns=['Feature','Number_of_Outliers'])
outlier_df

plt.figure(figsize=(7,7))

corr_matrix = df.corr(numeric_only=True)
print(corr_matrix)

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')

plt.title("Correlation Heatmap")
plt.show()

print("Target distribution:\n", df['PurchaseStatus'].value_counts(normalize=True))
plt.figure(figsize=(6,4))

sns.countplot(x='PurchaseStatus', data=df,palette='viridis')

plt.title("Distribution of Target Variable")
plt.xlabel("Purchase Status")
plt.ylabel("Count")

plt.show()

# --- B) Numeric distributions ---
for col in numeric_cols:  # show first 5
    plt.figure()
    sns.histplot(df[col], kde=True, bins=30)
    plt.title("Distribution of {}".format(col))
    plt.show()

label_encoder = LabelEncoder()

if df['ProductCategory'].dtype == 'object':
    df['ProductCategory'] = label_encoder.fit_transform(df['ProductCategory'])

"""# **Feature Engineering**"""

# Engagement Score
df['EngagementScore'] = (
    0.5 * df['TimeSpentOnWebsite'] +
    0.3 * df['NumberOfPurchases'] +
    0.2 * df['DiscountsAvailed']
)

# Recency-Frequency Indicator
df['RecencyFrequency'] = df['NumberOfPurchases'] / (df['TimeSpentOnWebsite'] + 1)

# Customer Activity Index
df['CustomerActivityIndex'] = (
    df['NumberOfPurchases'] * df['TimeSpentOnWebsite']
)

# Income Level Binning
df['IncomeLevel'] = pd.qcut(df['AnnualIncome'], 3, labels=[0,1,2])

"""# **Feature and Target Split**"""

X = df.drop('PurchaseStatus', axis=1)
y = df['PurchaseStatus']

X.columns

pd.qcut(df['AnnualIncome'], 3, labels=[0,1,2])

"""# **Train Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""
# **Standardization**"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train)

# Prediction
y_pred_log = log_model.predict(X_test_scaled)
y_train_pred= log_model.predict(X_train_scaled)
y_prob_log = log_model.predict_proba(X_test_scaled)[:,1]

print("Accuracy TRAIN:", accuracy_score(y_train,y_train_pred))
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Precision:", precision_score(y_test, y_pred_log))
print("Recall:", recall_score(y_test, y_pred_log))
print("F1 Score:", f1_score(y_test, y_pred_log))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob_log))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("Classification Report:\n", classification_report(y_test, y_pred_log))

param_grid = {
    "C": [0.01, 0.1, 1, 10]
}
log_grid = GridSearchCV(
    estimator=log_model,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

log_grid.fit(X_train_scaled, y_train)

print("Best Parameters", log_grid.best_params_)
print("Best CV score:", log_grid.best_score_)
best_log = log_grid.best_estimator_
# Prediction
y_train_predgrid= best_log.predict(X_train_scaled)
y_pred_loggrid= best_log.predict(X_test_scaled)
y_prob_loggrid= best_log.predict_proba(X_test_scaled)[:,1]

print("Accuracy TRAIN:", accuracy_score(y_train,y_train_predgrid))
print("Accuracy:", accuracy_score(y_test, y_pred_loggrid))
print("Precision:", precision_score(y_test, y_pred_loggrid))
print("Recall:", recall_score(y_test, y_pred_loggrid))
print("F1 Score:", f1_score(y_test, y_pred_loggrid))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob_loggrid))

log_grid_confu=confusion_matrix(y_test, y_pred_loggrid)
log_grid_class=classification_report(y_test, y_pred_loggrid)
print(log_grid_confu)
print(log_grid_class)

"""# **Compare with differnet Models,**

# Train and Predict all models
"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=200, random_state=42),
    "SVM": LinearSVC(),
    "XGBoost": xgb.XGBClassifier(n_estimators=200, random_state=42),
    "Naive Bayes": GaussianNB()
}
results = []
for name,model in models.items():
  model.fit(X_train_scaled, y_train)
  y_test_pred =model.predict(X_test_scaled)
  y_train_pred= log_model.predict(X_train_scaled)
  train_acc = accuracy_score(y_train, y_train_pred)
  test_acc = accuracy_score(y_test, y_test_pred)
  precision = precision_score(y_test, y_test_pred)
  recall = recall_score(y_test, y_test_pred)
  f1 = f1_score(y_test, y_test_pred)
  roc_auc = roc_auc_score(y_test, y_test_pred)
  results.append({"Model": name,
      "train accuracy": train_acc,
      "Test Accuracy": test_acc,
      "Precision": precision,
      "Recall": recall,
      "F1 Score": f1,
      "ROC AUC Score": roc_auc
                  })
results_df = pd.DataFrame(results)
results_df

results_df.sort_values(by=["F1 Score","Test Accuracy"],ascending=False,inplace=True)
results_df.reset_index(drop=True, inplace=True)
results_df

model=RandomForestClassifier(n_estimators=200,random_state=42,n_jobs=-1)
param_grid = {
    "n_estimators": [100, 200, 300],
    "max_depth": [3,5,8,10,20]
}
rf_grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

rf_grid.fit(X_train_scaled, y_train)
best_rf = rf_grid.best_estimator_
# Prediction
y_pred_rf = best_rf.predict(X_test_scaled)
y_prob_rf = best_rf.predict_proba(X_test_scaled)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob_rf))
#rf_confu=confusion_matrix(y_test, y_pred_rf)
print("\nConfusion Matrix:\n",confusion_matrix(y_test, y_pred_rf))
#rf_class=classification_report(y_test, y_pred_rf)
print("Classification Report:\n", classification_report(y_test, y_pred_rf))

gbmodel=GradientBoostingClassifier(n_estimators=200,random_state=42)
param_grid = {
    "n_estimators": [100, 200,300],
    "learning_rate": [0.01, 0.1, 0.2]
}
gb_grid = GridSearchCV(
    estimator=gbmodel,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

gb_grid.fit(X_train_scaled, y_train)
best_gb = gb_grid.best_estimator_
# Prediction
y_pred_gb = best_gb.predict(X_test_scaled)
y_prob_gb = best_gb.predict_proba(X_test_scaled)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred_gb))
print("Precision:", precision_score(y_test, y_pred_gb))
print("Recall:", recall_score(y_test, y_pred_gb))
print("F1 Score:", f1_score(y_test, y_pred_gb))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob_gb))
#gb_confu=confusion_matrix(y_test, y_pred_gb)
print("\nConfusion Matrix:\n",confusion_matrix(y_test, y_pred_gb))
print("\nClassification Report:\n",classification_report(y_test, y_pred_gb))

xgbmodel=xgb.XGBClassifier(n_estimators=200,random_state=42)
param_grid = {
    "n_estimators": [100,200,300],
    "learning_rate": [0.01, 0.05, 0.1,0.2]}

xgb_grid = GridSearchCV(
    estimator=xgbmodel,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

xgb_grid.fit(X_train_scaled, y_train)
best_xgb = xgb_grid.best_estimator_
# Prediction
y_pred_xgb = best_xgb.predict(X_test_scaled)
y_prob_xgb = best_xgb.predict_proba(X_test_scaled)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall:", recall_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb))
print("ROC AUC Score:", roc_auc_score(y_test, y_prob_xgb))

"""# **ROC Curve Comparison**"""

fpr,tpr,thresholds=roc_curve(y_test,y_prob_log)
aucscore_log=roc_auc_score(y_test,y_prob_log)

fpr1,tpr1,thresholds1=roc_curve(y_test,y_prob_rf)
aucscore_rf=roc_auc_score(y_test,y_prob_rf)

fpr2,tpr2,thresholds2=roc_curve(y_test,y_prob_gb)
aucscore_gb=roc_auc_score(y_test,y_prob_gb)

fpr3,tpr3,thresholds3=roc_curve(y_test,y_prob_xgb)
aucscore_xgb=roc_auc_score(y_test,y_prob_xgb)

plt.figure(figsize=(7,7))
plt.plot(fpr,tpr,label="Logistic Regression AUC={}".format(aucscore_log.round(2)))
plt.plot(fpr1,tpr1,label="Random Forest AUC={}".format(aucscore_rf.round(2)))
plt.plot(fpr2,tpr2,label="Gradient Boosting AUC={}".format(aucscore_gb.round(2)))
plt.plot(fpr3,tpr3,label="XGBoost AUC={}".format(aucscore_xgb.round(2)))
plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

model_names = ['Logistic Regression','Random Forest','Gradient Boosting','XGBoost']

accuracies = [
    accuracy_score(y_test, y_pred_log),
    accuracy_score(y_test, y_pred_rf),
    accuracy_score(y_test, y_pred_gb),
    accuracy_score(y_test, y_pred_xgb)
]

results_df = pd.DataFrame({
    'Model': model_names,
    'Accuracy': accuracies
})

plt.figure(figsize=(8,5))

sns.barplot(data=results_df, x='Model', y='Accuracy')

plt.title("Model Performance Comparison (Accuracy)")
plt.ylabel("Accuracy Score")
#plt.xticks(rotation=20)

plt.show()

model_names = ['Logistic Regression','Random Forest','Gradient Boosting','XGBoost']

recalls = [
    recall_score(y_test, y_pred_log),
    recall_score(y_test, y_pred_rf),
    recall_score(y_test, y_pred_gb),
    recall_score(y_test, y_pred_xgb)
]

results_df1 = pd.DataFrame({
    'Model': model_names,
    'Recall': recalls
})

plt.figure(figsize=(8,5))

sns.barplot(data=results_df1, x='Model', y='Recall')

plt.title("Model Performance Comparison (Recall)")
plt.ylabel("Recall Score")


plt.show()

model_names = ['Logistic Regression','Random Forest','Gradient Boosting','XGBoost']

f1scores = [
    f1_score(y_test, y_pred_log),
    f1_score(y_test, y_pred_rf),
    f1_score(y_test, y_pred_gb),
    f1_score(y_test, y_pred_xgb)
]

results_df2 = pd.DataFrame({
    'Model': model_names,
    'F1 Score': f1scores

})

results_df = pd.DataFrame({
    'Model': model_names,
    'F1Score': f1scores
})

plt.figure(figsize=(8,5))

sns.barplot(data=results_df, x='Model', y='F1Score')

plt.title("Model Performance Comparison (F1Score)")
plt.ylabel("F1Score")
plt.xticks(rotation=20)

plt.show()

importances = best_rf.feature_importances_
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(data=feature_importance, x='Importance', y='Feature')

plt.title("Feature Importance - Random Forest")
plt.show()

importances = best_gb.feature_importances_
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(data=feature_importance, x='Importance', y='Feature')

plt.title("Feature Importance - ")
plt.show()

importances = best_xgb.feature_importances_
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(data=feature_importance, x='Importance', y='Feature')

plt.title("Feature Importance - ")
plt.show()

# Create explainer
explainer = shap.TreeExplainer(best_xgb)
# Calculate SHAP values
shap_values = explainer.shap_values(X_test_scaled)
# Summary plot
shap.summary_plot(shap_values, X_test_scaled, feature_names=X.columns)

# Create explainer
explainer = shap.TreeExplainer(best_xgb)
# Calculate SHAP values
shap_values = explainer.shap_values(X_test_scaled)
# Summary plot
shap.summary_plot(shap_values, X_test_scaled, feature_names=X.columns, plot_type="bar")

joblib.dump(best_xgb, "purchase_model_xgb.pkl")

from google.colab import files
files.download("purchase_model_xgb.pkl")